//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *TCInjector) DeepCopyInto(out *TCInjector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopyObject implements the runtime.Object interface.
func (in *TCInjector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of this TCInjector.
func (in *TCInjector) DeepCopy() *TCInjector {
	if in == nil {
		return nil
	}
	out := new(TCInjector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *TCInjectorList) DeepCopyInto(out *TCInjectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TCInjector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements the runtime.Object interface.
func (in *TCInjectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of this TCInjectorList.
func (in *TCInjectorList) DeepCopy() *TCInjectorList {
	if in == nil {
		return nil
	}
	out := new(TCInjectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *TCInjectorSpec) DeepCopyInto(out *TCInjectorSpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]DelayRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this TCInjectorSpec.
func (in *TCInjectorSpec) DeepCopy() *TCInjectorSpec {
	if in == nil {
		return nil
	}
	out := new(TCInjectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *InjectedInterfaceStatus) DeepCopyInto(out *InjectedInterfaceStatus) {
	*out = *in
}

// DeepCopy returns a deep copy of this InjectedInterfaceStatus.
func (in *InjectedInterfaceStatus) DeepCopy() *InjectedInterfaceStatus {
	if in == nil {
		return nil
	}
	out := new(InjectedInterfaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *InjectedPodStatus) DeepCopyInto(out *InjectedPodStatus) {
	*out = *in
	if in.MultusInterfaces != nil {
		in, out := &in.MultusInterfaces, &out.MultusInterfaces
		*out = make([]InjectedInterfaceStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of this InjectedPodStatus.
func (in *InjectedPodStatus) DeepCopy() *InjectedPodStatus {
	if in == nil {
		return nil
	}
	out := new(InjectedPodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *TCInjectorStatus) DeepCopyInto(out *TCInjectorStatus) {
	*out = *in
	if in.InjectedPodDetails != nil {
		in, out := &in.InjectedPodDetails, &out.InjectedPodDetails
		*out = make([]InjectedPodStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this TCInjectorStatus.
func (in *TCInjectorStatus) DeepCopy() *TCInjectorStatus {
	if in == nil {
		return nil
	}
	out := new(TCInjectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *Target) DeepCopyInto(out *Target) {
	*out = *in
	if in.Primary != nil {
		in, out := &in.Primary, &out.Primary
		*out = new(bool)
		**out = **in
	}
	if in.MultusNetworks != nil {
		in, out := &in.MultusNetworks, &out.MultusNetworks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of this Target.
func (in *Target) DeepCopy() *Target {
	if in == nil {
		return nil
	}
	out := new(Target)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *DelayRule) DeepCopyInto(out *DelayRule) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(Target)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of this DelayRule.
func (in *DelayRule) DeepCopy() *DelayRule {
	if in == nil {
		return nil
	}
	out := new(DelayRule)
	in.DeepCopyInto(out)
	return out
}
