apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tc-injector-scc
rules:
  - apiGroups: [security.openshift.io]
    resources: [securitycontextconstraints]
    resourceNames: [tc-injector]
    verbs: [use]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tc-injector-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tc-injector-scc
subjects:
  - kind: ServiceAccount
    name: tc-injector
    namespace: tc-injector-system
